### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Seb-Solon** [Alignak-monitoring/alignak#262]
From previous Roadmap:
- [x] Pylint Code : End with Pylint rules naparuba/shinken#1393   #87 (@Seb-Solon, @titilambert, @gst)
- [ ] Doc enahcement : Add again some details about config objects (@alignak-monitoring)
- [x] Enhancement : Rework some utils functions naparuba/shinken#1493 (@Seb-Solon)
- [ ] Enhancement : Rework logger, differentiate naglog and shinken log: Issue=https://github.com/Alignak-monitoring/alignak/issues/70
    For refs, see naparuba/shinken#1525 and naparuba/shinken#1201
- [ ] Test stabilization: bad_start and full test
- [ ] Pypy compatibility
- [ ] Python 3 compat
- [x] Remove pickle and use Json #30 (@ddurieux)
- [ ] Enhancement: Ensure unicode in all stringProp (@Seb-Solon)
- [ ] Enhancement: Default value for ListProp ([] or [''] or None ?)
- [x] Rename alignak modules parameters : module_name and module_type

No Release date
