### ISSUE TITLE
Roadmap 0.1

### ISSUE THREAD

**Issue by Seb-Solon** [Alignak-monitoring/alignak#4]
- [x] Pylint Code : Remove all skip file naparuba/shinken#1393   #87 (@Seb-Solon, @titilambert, @gst)
- [x] Update doc to setup develop environment #88
- [x] Enhancement: Refactor list parsing in configuration (empty string should be casted "[]" or "None") (ie: contactgroups parameter) naparuba/shinken#1468  
- [x] Enhancement : Remove dead code detected naparuba/shinken#1483 naparuba/shinken#1430 (@Seb-Solon)
- [x] Test : Add functional tests #89 
- [x] Add setup tests #73 #102
- [x] Add python namespace for Alignak : #90 (@titilambert)
- [x] Regenerates file header to list all contributors #TDB (@Seb-Solon)
- [x] Remove unrelevant files. #91 ( #58, #57, etc.. ) 
- [x] Clean the http_daemon #53 #189 (@Seb-Solon)
- [x] Clean/rewrite the http_client modules #80 
- [ ] Packaging #174
- [x] Website on github.io (@ddurieux)
- [x] Check request lib == 2.6.0 with python2.6 and python2.7 (@gst or anyone else)

**Comment by gst** [comment]
> Enhancement: Refactor list parsing in configuration (empty string should be casted "[]" or "None") (ie: contactgroups parameter) 

Concerning this item, imho, any configuration attribute/directive which can contain multiple values, often (if not always ? which would be better..) separated by commas, should **always** result in a list assigned to that attribute at the object level. Whatever are the actual number of values given for the attribute (0 / 1 / more..). Hardcoded default list values could be used for some attributes, as it is right now but in anyway the `type(obj.attribute)` should always be `list` ; not `NoneType`. That would simplify the logic at quite some place in the code where sometimes there are pattern/things like : 
```
if  obj.attr is not None:   # or shorter:   if obj.attr:
    for item in obj.attr:
        # do something with item
```

**Comment by gst** [comment]
> Enhancement : Rework logger, differanciate naglog and shinken log naparuba/shinken#1525 naparuba/shinken#1201

+1

**Comment by titilambert** [comment]
What do you mean by "naglog" ?

**Comment by gst** [comment]
>  What do you mean by "naglog" ?

```
def naglog_result(level, result, *args):
    """
    Function use for old Nag compatibility. We to set format properly for this call only.

    Dirty Hack to keep the old format, we should have another logger and
    use one for Shinken logs and another for monitoring data
    """
```

**Comment by gst** [comment]
> Enhancement: Ensure unicode in all stringProp (@Seb-Solon)

I guess you mean that, for every stringprop, we must result in a unicode string stored in the object attribute, not a byte string ?  if yes : +100000
